"""Add NGO fields

Revision ID: 4c2761174c75
Revises: b164c6634f3a
Create Date: 2026-06-28 10:52:51.233949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2761174c75'
down_revision = 'b164c6634f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ngo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ngo_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('ngo_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('upi_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('upi_id')
        batch_op.drop_column('ngo_description')
        batch_op.drop_column('ngo_name')
        batch_op.drop_column('is_ngo')

    # ### end Alembic commands ###
