"""Add NGO tracking and gallery

Revision ID: 571014a2bc59
Revises: d2b4ebbd9b46
Create Date: 2026-07-02 20:07:04.102722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571014a2bc59'
down_revision = 'd2b4ebbd9b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngo_gallery_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ngo_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upi_donation_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ngo_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upi_donation_clicks')
    op.drop_table('ngo_gallery_images')
    # ### end Alembic commands ###
