"""Remove premium features

Revision ID: 79e2584b51e3
Revises: 4c2761174c75
Create Date: 2026-06-30 19:42:37.517649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e2584b51e3'
down_revision = '4c2761174c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('is_premium')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_premium_donor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium_donor', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
