"""Add impact and user ratings

Revision ID: 90b9dade661c
Revises: 571014a2bc59
Create Date: 2026-07-07 19:27:27.785487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b9dade661c'
down_revision = '571014a2bc59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('rated_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rated_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('usage_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('impact_message', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('user', 'admin', name='user_roles'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('user', 'admin', name='user_roles'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('donation_history', schema=None) as batch_op:
        batch_op.drop_column('impact_message')
        batch_op.drop_column('usage_photo')
        batch_op.drop_column('receipt_photo')

    op.drop_table('user_ratings')
    # ### end Alembic commands ###
