"""Add image columns

Revision ID: d2b4ebbd9b46
Revises: 7ed2aee4cc75
Create Date: 2026-07-02 19:52:11.804380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b4ebbd9b46'
down_revision = '7ed2aee4cc75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ngo_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ngo_image')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
